<?php

namespace FondOfSpryker\Zed\Contentful\Communication\Console;

use Spryker\Zed\Kernel\Communication\Console\Console;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class ContentfulSearchExportConsole extends Console
{
    private const COMMAND_NAME = 'contentful:export:search';
    private const DESCRIPTION = 'Exports all entries form table fos_contentful_entry to search.';

    /**
     * @return void
     */
    protected function configure(): void
    {
       $this->setName(static::COMMAND_NAME);
       $this->setDescription(static::DESCRIPTION);
    }

    /**
     * @param \Symfony\Component\Console\Input\InputInterface $input
     * @param \Symfony\Component\Console\Output\OutputInterface $output
     *
     * @return int|void|null
     */
    protected function execute(InputInterface $input, OutputInterface $output)
    {
        parent::execute($input, $output); // TODO: Change the autogenerated stub
    }
}
